(synth-fun mainventry () Bool)
(synth-fun mainv_9 ((x0 Int)) Bool)
(synth-fun mainv_12 ((x0 Int)) Bool)
(synth-fun mainvverifier.error ((x0 Int) ) Bool)
(synth-fun mainvverifier.error.split () Bool)
(synth-fun mainventry!_BAD () Bool)
(synth-fun mainv_9!_FwdCond ((x0 Int)) Bool)
(declare-var mainv%_15_0 Bool )
(declare-var mainv%_13_0 Int )
(declare-var vg_0 Int )
(declare-var mainv%_10_0 Int )
(declare-var vfind_condition_0 Int )
(declare-var mainv%_11_0 Bool )
(declare-var mainv%_0_0 Int )
(declare-var vnd_0 Int )
(declare-var mainv%_1_0 Int )
(declare-var mainv%_2_0 Int )
(declare-var mainv%_3_0 Int )
(declare-var mainv%_4_0 Int )
(declare-var mainv%_7_0 Bool )
(declare-var mainventry_0 Bool )
(declare-var mainv%_6_0 Int )
(declare-var mainv_8_0 Bool )
(declare-var mainv_9_0 Bool )
(declare-var |tuple(mainventry_0, mainv_9_0)| Bool )
(declare-var mainv%.0.i_0 Int )
(declare-var mainv%.0.i_1 Int )
(declare-var mainv%.0.i_2 Int )
(declare-var mainv_12_0 Bool )
(declare-var mainvverifier.error_0 Bool )
(declare-var mainv%.1.i_0 Int )
(declare-var mainv%.1.i_1 Int )
(declare-var mainv%_14_0 Int )
(declare-var mainvverifier.error.split_0 Bool )
(constraint mainventry)
(constraint (=> (and mainventry
                (= mainv%_6_0 (+ mainv%_3_0 mainv%_1_0))
                (= mainv%_7_0 (> mainv%_6_0 8))
                (= mainv%.0.i_0 mainv%_6_0)
                (= mainv%.0.i_1 9)
                (=> mainv%_7_0 (= mainv%.0.i_2 mainv%.0.i_0))
                (=> (not mainv%_7_0) (= mainv%.0.i_2 mainv%.0.i_1)))
  (mainv_9 mainv%.0.i_2 )))
(constraint (=> (and (mainv_12 mainv%.0.i_0)
         (= mainv%.1.i_1 (+ mainv%.0.i_0 (- 1))))
    (mainvverifier.error mainv%.1.i_1)))
(constraint (=> (and (mainvverifier.error mainv%.1.i_0)
         (not (> mainv%.1.i_0 8)))
    mainvverifier.error.split))
(constraint (=> (and (mainv_9!_FwdCond mainv%.0.i_0)
         (mainv_9 mainv%.0.i_0))
    (mainv_12 mainv%.0.i_0)))
(constraint (=> (and (not (mainv_9!_FwdCond mainv%.0.i_0))
         (mainv_9 mainv%.0.i_0))
    (mainvverifier.error mainv%.0.i_0)))
(constraint (=> mainvverifier.error.split false))
(check-synth)
